@ItsWdfs.Csharp._20240124.Program20240124WebApi1_HostAddress = http://localhost:5090

GET {{ItsWdfs.Csharp._20240124.Program20240124WebApi1_HostAddress}}/weatherforecast/
Accept: application/json

###
